# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY api/ ./api
RUN pip install -r ./api/requirements.txt
ENV FLASK_ENV production

WORKDIR /app/api
EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
